# Language
export LC_ALL=en_US.UTF-8
export LANG=en_us.UTF-8


# Install fzf
if [ ! -d "$HOME/.fzf" ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install --all
fi

# Setting fdfind as the default source for fzf
# export FZF_DEFAULT_COMMAND='fdfind --type f --strip-cwd-prefix'
export FZF_DEFAULT_COMMAND='fdfind --hidden'

# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

# Enable kube-ps1
# zinit ice wait="0a" lucid atload="_kube_ps1_prompt_update"
zinit light jonmosco/kube-ps1

# Install powerlevel10k
zinit ice depth=1; zinit light romkatv/powerlevel10k

# Plugin to update terminal title
zinit light trystan2k/zsh-tab-title

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Enable compinit and replay compdefs
autoload -Uz compinit
compinit
zinit cdreplay -q
zstyle ':completion:*' menu select
# Enable case insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# autosuggestions, trigger precmd hook upon load
# ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
# zinit ice wait="0a" lucid atload="_zsh_autosuggest_start"
# zinit light zsh-users/zsh-autosuggestions

PROMPT_EOL_MARK=""

# Load helper functions
source ~/.zshrc.helpers
source_if_exists ~/.zshrc.aliases
source_if_exists ~/.fzf.zsh

case "$OSTYPE" in
    linux*)
        source_if_exists ~/.zshrc.linux
        ;;
    darwin*)
        source_if_exists ~/.zshrc.macos
        ;;
esac

source_if_exists ~/.zshrc.tokens
source_if_exists ~/.zshrc.dd

# Enable colors
autoload -U colors && colors

# Editor
export EDITOR="nvim"

# set vi editing mode
bindkey -v
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

# History - from https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/history.zsh
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=50000
export SAVEHIST=10000
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data


# Add dirs to path
export PATH="$HOME/bin:/usr/local/sbin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH=${HOME}/src/team-aaa-internal-tools/scripts:${PATH}
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

export DATADOG_SHELL_USER="chris.linstid"

export LESS="--no-init --quit-if-one-screen -R"

alias vim=nvim

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

if command -v kubectl &> /dev/null; then
    source <(kubectl completion zsh)
fi

if [ -d "$HOME/.volta" ]; then
    export VOLTA_HOME="$HOME/.volta"
    export PATH="$VOLTA_HOME/bin:$PATH"
fi

git machete --version &> /dev/null && source <(git machete completion zsh)

SCRIPT=~/dd/winter/winter/completion-scripts/winter_completion.zsh && test -f $SCRIPT && source $SCRIPT
