# Language
export LC_ALL=en_US.UTF-8
export LANG=en_us.UTF-8


# Install fzf
if [ ! -d "$HOME/.fzf" ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
fi

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

# Enable kube-ps1
zinit light jonmosco/kube-ps1

# Install powerlevel10k
zinit ice depth=1; zinit light romkatv/powerlevel10k

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Enable compinit and replay compdefs
autoload -Uz compinit
compinit
zinit cdreplay -q
zstyle ':completion:*' menu select

# autosuggestions, trigger precmd hook upon load
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
zinit ice wait="0a" lucid atload="_zsh_autosuggest_start"
zinit light zsh-users/zsh-autosuggestions

PROMPT_EOL_MARK=""

# Load helper functions
source ~/.zshrc.helpers
source_if_exists ~/.zshrc.aliases
source_if_exists ~/.fzf.zsh

case "$OSTYPE" in
    linux*)
        source_if_exists ~/.zshrc.linux
        ;;
    darwin*)
        source_if_exists ~/.zshrc.macos
        ;;
esac

source_if_exists ~/.zshrc.tokens
source_if_exists ~/.zshrc.dd

# Enable colors
autoload -U colors && colors

# Editor
export EDITOR="nvim"

# set vi editing mode
bindkey -v
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

# History

# Appends every command to the history file once it is executed
setopt inc_append_history

# Reloads the history whenever you use it
setopt share_history


# Add dirs to path
export PATH="$HOME/bin:/usr/local/sbin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH=${HOME}/src/team-aaa-internal-tools/scripts:${PATH}
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

export DATADOG_SHELL_USER="chris.linstid"

export LESS="--no-init --quit-if-one-screen -R"

alias vim=nvim

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
