config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
variables:
  is_workspace: false
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zshrc.macos:
    src: zshrc.macos
    dst: ~/.zshrc.macos
    chmod: '600'
  f_zshrc.helpers:
    src: zshrc.helpers
    dst: ~/.zshrc.helpers
  f_zshrc.aliases:
    src: zshrc.aliases
    dst: ~/.zshrc.aliases
  f_zshrc.dd:
    src: zshrc.dd
    dst: ~/.zshrc.dd
  f_zshrc.tokens:
    src: zshrc.tokens
    dst: ~/.zshrc.tokens
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  d_ftplugin:
    src: vim/ftplugin
    dst: ~/.vim/ftplugin
  f_vimrc-coc:
    src: vimrc-coc
    dst: ~/.vimrc-coc
  f_zshrc.linux:
    src: zshrc.linux
    dst: ~/.zshrc.linux
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_gitignore:
    src: gitignore
    dst: ~/.gitignore
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  f_toprc:
    src: config/procps/toprc
    dst: ~/.config/procps/toprc
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_main.code-workspace:
    src: main.code-workspace
    dst: ~/main.code-workspace
  f_btop.conf:
    src: config/btop/btop.conf
    dst: ~/.config/btop/btop.conf
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
  f_ssh_github.pub:
    src: ssh/github.pub
    dst: ~/.ssh/github.pub
profiles:
  common:
    dotfiles:
    - f_zshrc
    - f_zshrc.helpers
    - f_zshrc.aliases
    - f_zshrc.dd
    - f_zshrc.tokens
    - f_p10k.zsh
    - d_nvim
    - f_vimrc
    - d_ftplugin
    - f_vimrc-coc
    - f_gitconfig
    - f_gitignore
    - f_tmux.conf
    - f_btop.conf
  macos:
    dotfiles:
    - f_zshrc.macos
  linux:
    dotfiles:
    - f_zshrc.linux
    - f_toprc
  warmachine:
    include:
    - common
    - macos
    dotfiles:
    - f_p10k.zsh
  ironman:
    include:
    - common
    - macos
    dotfiles:
    - f_p10k.zsh
  workspace:
    include:
    - common
    - linux
    variables:
      is_workspace: true
    dotfiles:
    - f_main.code-workspace
    - f_ssh_config
    - f_ssh_github.pub
  chris-linstid-0:
    include:
    - workspace
  chris-linstid-green-0:
    include:
    - workspace
  chris-linstid-blue-0:
    include:
    - workspace
  chris-linstid-red-0:
    include:
    - workspace
